resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.4.2

resources:
- name: rocket-chat-staging
  type: cf
  icon: cloud-upload
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    organization: ((cf.org))
    space: ((cf.space))
    skip_cert_check: false

- name: seronet-rocket-chat
  type: git
  icon: github-face
  source:
    uri: git@github.com:seronet-project/Rocket.Chat.git
    branch: develop
    depth: 5
    disable_ci_skip: false
    private_key: ((github-private-key))

- name: rocket-chat-rocket-chat
  type: git
  icon: github-face
  source:
    uri: https://github.com/RocketChat/Rocket.Chat.git
    branch: develop
    depth: 30

- name: notify
  type: slack-notification
  icon: chat-alert
  source:
    url: ((slack-webhook))

- name: merge-timer
  type: time
  source:
    start: 2:30 AM
    stop: 3:30 AM
    location: Europe/Berlin

jobs:
- name: merge-rocket-chat
  public: false
  serial_groups: ["rocket-chat"]
  plan:
  - get: merge-timer
    trigger: true
  - get: rocket-chat-rocket-chat
#    trigger: true
  - get: seronet-rocket-chat
  - task: merge-rocket-chat-develop
    config:
      platform: linux
      inputs:
      - name: seronet-rocket-chat
      outputs:
      - name: seronet-rocket-chat
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs3
      run:
        path: bash
        args:
        - -exc
        - |
          cd seronet-rocket-chat
          git config user.email "concourse@sero.network"
          git config user.name "SeRoNet Concourse"
          git remote add rocket.chat https://github.com/RocketChat/Rocket.Chat.git
          git fetch rocket.chat develop
          git merge --no-edit rocket.chat/develop
  - put: seronet-rocket-chat
    params:
      repository: seronet-rocket-chat

- name : deploy-rocket-chat
  serial_groups: ["rocket-chat"]
  plan:
    - get: seronet-rocket-chat
      trigger: true
    - task: rocket-chat-prebuild
      config:
        platform: linux
        inputs:
          - name: seronet-rocket-chat
        outputs:
          - name: rocket-chat-out
          - name: rocket-chat-build
        image_resource:
          type: docker-image
          source:
            repository: node
            tag: 12.18.0
        run:
          user: root
          path: sh
          args:
          - -exc
          - |
            command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh
            # apt-get update && apt-get install -y build-essential
            node -v
            export METEOR_ALLOW_SUPERUSER=true
            meteor --version
            cp -r seronet-rocket-chat/. rocket-chat-build
            cd rocket-chat-build
            meteor npm install
            meteor npm run postinstall
            meteor build --server-only --directory ../rocket-chat-out
            cp manifest.yml ../rocket-chat-out
            cd ../rocket-chat-out
            node -v > bundle/.nvmrc
            ls bundle
            cd bundle/programs/server
            npm install
            cd -
            chmod -R u+rw bundle
    - put: rocket-chat-staging
      params:
        manifest: rocket-chat-out/manifest.yml
#        environment_variables:
      on_success:
        put: notify
        params:
          text: "Rocket Chat deployed to ((cf.space)) in ((cf.org))."
      on_failure:
        put: notify
        params:
          text: "Failed to deploy Rocket.Chat to ((cf.space)) in ((cf.org))."